import { PreviewTemplateDefinition } from '@/types/preview';

export const PREVIEW_TEMPLATES: PreviewTemplateDefinition[] = [
  {
    id: 'template-runners-zine',
    name: "Runner's Zine",
    defaultBackground: 'activity-photo',
    defaultBlurEffectId: 'background-blur',
    showRoute: true,
    routeTransform: {
      x: 170,
      y: 530,
      scale: 0.5,
    },
    layerStyleOverrides: {
      route: { color: '#F5F5F5', opacity: 1 },
    },
    fixedImageElements: [
      {
        id: 'title-logo',
        name: 'Runner zine title',
        asset: require('../assets/templates/runners-world-logo.png'),
        isBehind: true,
        x: 10,
        y: 10,
        width: 340,
        height: 92,
      },
    ],
    fixedTextElements: [
      {
        id: 'meta-location',
        text: '{location} EDITION',
        uppercase: true,
        x: 10,
        y: 90,
        color: 'transparent',
        fontFamily: 'Avenir Next',
        backgroundColor: '#ffffff',
        fontSize: 16,
        fontWeight: '900',
        letterSpacing: 0.3,
        isBehind: true,
      },
      {
        id: 'elev-value',
        text: '{elev}',
        x: 10,
        y: 444,
        color: '#d7000c',
        fontFamily: 'Monoton',
        fontSize: 42,
        fontWeight: '900',
      },
      {
        id: 'elev-label',
        text: 'Of elevation\ngain',
        uppercase: true,
        x: 14,
        y: 488,
        color: '#FFFFFF',
        fontSize: 14,
        fontFamily: 'Avenir Next',
        fontWeight: '800',
        letterSpacing: 0.8,
      },
      {
        id: 'hr-value',
        text: 'A steady\n[[{avgHr}]]\naverage',
        requiredDataFields: ['avgHr'],
        x: 256,
        y: 180,
        color: '#ffffff',
        accentColor: '#d7000c',
        accentFontWeight: '900',
        fontSize: 16,
        fontFamily: 'Avenir Next',
        fontWeight: '700',
        uppercase: true,
        borderColor: '#ffffff',
        borderWidth: 4,
        borderRadius: 200,
        paddingX: 12,
        paddingY: 20,
      },
      {
        id: 'calories-label',
        text: 'CALORIES\nBURNED',
        requiredDataFields: ['calories'],
        x: 260,
        y: 400,
        color: '#d7000c',
        fontSize: 15,
        fontWeight: '900',
        letterSpacing: 0.8,
        fontFamily: 'Avenir Next',
      },
      {
        id: 'calories-value',
        text: '{calories}',
        requiredDataFields: ['calories'],
        x: 260,
        y: 364,
        color: '#FFFFFF',
        fontSize: 30,
        fontWeight: '900',
      },
      {
        id: 'story-copy',
        text: 'Inside a [[{time}]] run over [[{distance}]].\nCruising at [[{pace}]] pace.',
        uppercase: true,
        x: 14,
        y: 160,
        width: 120,
        color: '#FFFFFF',
        opacity: 0.96,
        fontSize: 18,
        lineHeight: 18 * 1.2,
        fontWeight: '600',
        letterSpacing: 0.15,
        accentFontSize: 24,
        accentFontWeight: '900',
        accentLetterSpacing: 0.2,
        fontFamily: 'Helvetica Neue',
      },
      {
        id: 'meta-date',
        text: '{date}',
        x: 22,
        y: 586,
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.3,
      },
      {
        id: 'meta-name',
        text: '{activityName}',
        uppercase: true,
        x: 22,
        y: 602,
        color: '#d7000c',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
      },
    ],
  },
  {
    id: 'template-polaroid',
    name: 'Polaroid',
    disableBackgroundRemoval: true,
    disableVideoBackground: true,
    imagePickerCropSize: {
      width: 650,
      height: 735,
    },
    defaultBackground: 'activity-photo',
    backgroundMediaFrame: {
      x: 70,
      y: 118,
      width: 260,
      height: 294,
      mediaScale: 1,
      mediaOffsetX: 0,
      mediaOffsetY: 0,
      fit: 'width-crop-center',
    },
    fixedImageElements: [
      {
        id: 'polaroid-bg',
        name: 'Polaroid background',
        asset: require('../assets/templates/polaroid-template.png'),
        x: 0,
        y: 0,
        width: 360,
        height: 640,
      },
    ],
    fixedTextElements: [
      {
        id: 'meta-date',
        text: '{date}',
        formatDate: 'mm/dd/YYYY',
        uppercase: true,
        x: 62,
        y: 348,
        color: 'orange',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Courier New',
        width: 248,
      },
      {
        id: 'meta-name',
        text: '{activityName}',
        uppercase: true,
        x: 62,
        y: 382,
        color: '#000000',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 248,
      },
      {
        id: 'run-distance-location',
        text: 'Run {distance} - {location}',
        uppercase: true,
        x: 62,
        y: 408,
        color: '#000000',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 248,
      },
      {
        id: 'time-label',
        text: '{time}',
        uppercase: true,
        x: 62,
        y: 424,
        color: '#000000',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 248,
      },
      {
        id: 'pace-label',
        text: '{pace} pace',
        uppercase: true,
        x: 62,
        y: 440,
        color: '#000000',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 248,
      },
      {
        id: 'elev-label',
        text: '{elev} of elevation gain',
        uppercase: true,
        x: 62,
        y: 456,
        color: '#000000',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 248,
      },
      {
        id: 'hr-label',
        text: '{avgHr}',
        uppercase: true,
        x: 62,
        y: 472,
        color: '#000000',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 248,
      },
      {
        id: 'cal-label',
        text: '{calories} calories',
        uppercase: true,
        x: 62,
        y: 488,
        color: '#000000',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 248,
      },
    ],
  },
];

export const DEFAULT_PREVIEW_TEMPLATE_ID =
  PREVIEW_TEMPLATES[0]?.id ?? 'template-runners-zine';

export function getPreviewTemplateById(templateId: string | null | undefined) {
  if (!templateId) return null;
  return PREVIEW_TEMPLATES.find((item) => item.id === templateId) ?? null;
}
