import { PreviewTemplateDefinition } from '@/types/preview';

export const PREVIEW_TEMPLATES: PreviewTemplateDefinition[] = [
  {
    id: 'template-cover',
    name: 'Cover',
    defaultBackground: 'activity-photo',
    defaultBlurEffectId: 'background-blur',
    showRoute: true,
    routeTransform: {
      x: 170,
      y: 530,
      scale: 0.5,
    },
    layerStyleOverrides: {
      route: { color: '#F5F5F5', opacity: 1 },
    },
    fixedImageElements: [
      {
        id: 'title-logo',
        name: 'Runner zine title',
        asset: require('../assets/templates/runner.png'),
        isBehind: true,
        x: 10,
        y: 35,
        width: 340,
        height: 92,
      },
    ],
    fixedTextElements: [
      {
        id: 'meta-date',
        text: '{date}',
        uppercase: true,
        x: 10,
        y: 10,
        width: 340,
        formatDate: 'mm/dd/YYYY',
        color: 'transparent',
        backgroundColor: '#ffffff',
        fontFamily: 'Avenir Next',
        fontSize: 15,
        fontWeight: '700',
        letterSpacing: 0.3,
        align: 'right',
        paddingX: 14,
        isBehind: true,
      },
      {
        id: 'meta-location',
        text: '{location} Edition',
        uppercase: true,
        x: 10,
        y: 120,
        width: 340,
        textAlign: 'left',
        color: 'transparent',
        fontFamily: 'Avenir Next',
        backgroundColor: '#ffffff',
        fontSize: 15,
        fontWeight: '700',
        letterSpacing: 0.3,
        isBehind: true,
      },
      {
        id: 'story-copy',
        text: 'Inside a [[{time}]] run over [[{distance}]].\nCruising at [[{pace}]] pace.',
        uppercase: true,
        x: 14,
        y: 180,
        width: 120,
        color: '#FFFFFF',
        opacity: 0.96,
        fontSize: 18,
        lineHeight: 18 * 1.2,
        fontWeight: '600',
        letterSpacing: 0.15,
        accentFontSize: 24,
        accentFontWeight: '900',
        accentLetterSpacing: 0.2,
        fontFamily: 'Helvetica Neue',
      },
      {
        id: 'hr-value',
        text: 'A steady\n[[{avgHr}]]\naverage',
        requiredDataFields: ['avgHr'],
        x: 256,
        y: 200,
        color: '#ffffff',
        accentColor: '#d7000c',
        accentFontWeight: '900',
        fontSize: 16,
        fontFamily: 'Avenir Next',
        fontWeight: '700',
        uppercase: true,
        borderColor: '#ffffff',
        borderWidth: 4,
        borderRadius: 200,
        paddingX: 12,
        paddingY: 20,
      },
      {
        id: 'elev-value',
        text: '{elev}',
        x: 10,
        y: 444,
        color: '#d7000c',
        fontFamily: 'Monoton',
        fontSize: 42,
        fontWeight: '900',
      },
      {
        id: 'elev-label',
        text: 'Of elevation\ngain',
        uppercase: true,
        x: 14,
        y: 488,
        color: '#FFFFFF',
        fontSize: 14,
        fontFamily: 'Avenir Next',
        fontWeight: '800',
        letterSpacing: 0.8,
      },
      {
        id: 'calories-label',
        text: 'CALORIES\nBURNED',
        requiredDataFields: ['calories'],
        x: 260,
        y: 400,
        color: '#d7000c',
        fontSize: 15,
        fontWeight: '900',
        letterSpacing: 0.8,
        fontFamily: 'Avenir Next',
      },
      {
        id: 'calories-value',
        text: '{calories}',
        requiredDataFields: ['calories'],
        x: 260,
        y: 364,
        color: '#FFFFFF',
        fontSize: 30,
        fontWeight: '900',
      },
      {
        id: 'meta-name',
        text: '{activityName}',
        uppercase: true,
        x: 22,
        y: 602,
        color: '#d7000c',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        width: 320,
        align: 'left',
      },
    ],
  },
  {
    id: 'template-polaroid',
    name: 'Polaroid',
    disableBackgroundRemoval: true,
    disableVideoBackground: true,
    defaultFilterEffectId: 'cool-night',
    imagePickerCropSize: {
      width: 650,
      height: 735,
    },
    defaultBackground: 'activity-photo',
    backgroundMediaFrame: {
      x: 32,
      y: 44,
      width: 340,
      height: 384,
      mediaScale: 1,
      mediaOffsetX: 0,
      mediaOffsetY: 0,
      fit: 'width-crop-center',
    },
    fixedImageElements: [
      {
        id: 'polaroid-bg',
        name: 'Polaroid background',
        asset: require('../assets/templates/polaroid-wood.png'),
        x: 0,
        y: 0,
        width: 360,
        height: 640,
      },
    ],
    fixedTextElements: [
      {
        id: 'meta-date',
        text: '{date}',
        formatDate: 'mm/dd/YYYY',
        uppercase: true,
        x: 32,
        y: 360,
        color: 'orange',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Courier New',
        width: 300,
      },
      {
        id: 'meta-name',
        text: '{activityName}',
        uppercase: true,
        x: 32,
        y: 406,
        color: '#000000',
        fontSize: 20,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 300,
      },
      {
        id: 'run-distance-location',
        text: 'Run {distance} - {location}',
        x: 32,
        y: 442,
        color: '#000000',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 300,
      },
      {
        id: 'time-label',
        text: '{time}',
        x: 32,
        y: 460,
        color: '#000000',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 300,
      },
      {
        id: 'pace-label',
        text: '{pace} pace',
        x: 32,
        y: 478,
        color: '#000000',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 300,
      },
      {
        id: 'elev-label',
        text: '{elev} of elevation gain',
        x: 32,
        y: 496,
        color: '#000000',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 300,
      },
      {
        id: 'hr-label',
        text: '{avgHr}',
        x: 32,
        y: 514,
        color: '#000000',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 300,
      },
      {
        id: 'cal-label',
        text: '{calories} calories',
        x: 32,
        y: 532,
        color: '#000000',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Bradley Hand',
        width: 300,
      },
    ],
  },
  {
    id: 'template-neon',
    name: 'Neon',
    showBackgroundTab: false,
    defaultBackground: 'none',
    fixedImageElements: [
      {
        id: 'grid-bg',
        name: 'Grid background',
        asset: require('../assets/templates/grid-bg.png'),
        x: 0,
        y: 0,
        width: 360,
        height: 640,
      },
    ],
    fixedTextElements: [
      {
        id: 'distance-label',
        text: 'Distance',
        uppercase: true,
        x: 23,
        y: 76,
        color: '#a1a1a1',
        fontSize: 14,
        fontWeight: '400',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
      },
      {
        id: 'distance-value',
        text: '[[{distanceValue}]] {distanceUnit}',
        uppercase: true,
        x: 28,
        y: 100,
        color: '#a9e450',
        fontSize: 14,
        fontWeight: '400',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
        accentFontSize: 28,
        accentFontWeight: '500',
        lineHeight: 32,
        borderColor: '#5a5a5a',
        borderWidth: 1,
        borderRadius: 0,
        paddingX: 4,
        paddingY: 4,
        width: 104,
        align: 'center',
      },
      {
        id: 'hr-label',
        text: 'AVG HR',
        uppercase: true,
        x: 131,
        y: 76,
        color: '#a1a1a1',
        fontSize: 14,
        fontWeight: '400',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
      },
      {
        id: 'hr-value',
        text: '[[{avgHrValue}]] {avgHrUnit}',
        uppercase: true,
        x: 136,
        y: 100,
        color: '#a9e450',
        fontSize: 14,
        fontWeight: '400',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
        accentFontSize: 28,
        accentFontWeight: '500',
        lineHeight: 32,
        borderColor: '#5a5a5a',
        borderWidth: 1,
        borderRadius: 0,
        paddingX: 4,
        paddingY: 4,
        width: 92,
        align: 'center',
      },
      {
        id: 'cal-label',
        text: 'Calories',
        uppercase: true,
        x: 227,
        y: 76,
        color: '#a1a1a1',
        fontSize: 14,
        fontWeight: '400',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
      },
      {
        id: 'cal-value',
        text: '[[{calories}]] Cal',
        uppercase: true,
        x: 232,
        y: 100,
        color: '#a9e450',
        fontSize: 14,
        fontWeight: '400',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
        accentFontSize: 28,
        accentFontWeight: '500',
        lineHeight: 32,
        borderColor: '#5a5a5a',
        borderWidth: 1,
        borderRadius: 0,
        paddingX: 4,
        paddingY: 4,
        width: 104,
        align: 'center',
      },
      {
        id: 'pace-label',
        text: '[[{paceValue}]] {paceUnit}',
        uppercase: true,
        x: 0,
        y: 640 / 2 - 80,
        color: '#b1ec5e',
        fontSize: 32,
        fontWeight: '400',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
        width: 360,
        align: 'center',
        glowColor: '#b1ec5e',
        glowRadius: 8,
        accentFontSize: 90,
        accentFontWeight: '400',
        lineHeight: 94,
      },
      {
        id: 'elev-label',
        text: '+{elev}',
        uppercase: true,
        x: 260,
        y: 640 / 2 - 100,
        color: '#a9e450',
        fontSize: 16,
        fontWeight: '500',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
        width: 300,
      },
      {
        id: 'meta-date-location',
        text: '{date} - {location}',
        formatDate: 'mm/dd/YYYY',
        uppercase: true,
        x: 0,
        y: 486,
        color: '#a1a1a1',
        fontSize: 12,
        fontWeight: '400',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
        width: 360,
        align: 'right',
        paddingX: 26,
      },
      {
        id: 'time-label',
        text: 'Duration     [[{time}]]',
        uppercase: true,
        x: 32,
        y: 524,
        color: '#a1a1a1',
        fontSize: 14,
        fontWeight: '400',
        accentColor: '#a9e450',
        accentFontSize: 24,
        accentFontWeight: '400',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
      },
      {
        id: 'meta-name',
        text: '{activityName}',
        uppercase: true,
        x: 32,
        y: 556,
        color: '#a1a1a1',
        fontSize: 14,
        fontWeight: '400',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
      },
    ],
    fixedChartElements: [
      {
        id: 'pace-chart-a',
        kind: 'pace',
        x: 360 / 2 - 100,
        y: 380,
        width: 200,
        height: 90,
        color: '#a9e450',
        showAxes: true,
        showGrid: false,
        orientation: 'vertical',
        fillStyle: 'gradient',
      },
    ],
  },
  {
    id: 'template-ticket',
    name: 'Ticket',
    showBackgroundTab: false,
    defaultBackground: 'none',
    showRoute: true,
    routeTransform: {
      x: 122,
      y: 382,
      scale: 0.7,
    },
    layerStyleOverrides: {
      route: { color: '#101010', opacity: 0.8 },
    },
    fixedImageElements: [
      {
        id: 'grid-bg',
        name: 'Grid background',
        asset: require('../assets/templates/ticket-run.png'),
        isBehind: true,
        x: 0,
        y: 0,
        width: 360,
        height: 640,
      },
    ],
    fixedTextElements: [
      {
        id: 'distance-label',
        text: '[[{distanceValue}]] {distanceUnit}',
        uppercase: true,
        x: 22,
        y: 120,
        color: '#101010',
        fontSize: 32,
        accentFontSize: 72,
        lineHeight: 76,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Helvetica Neue',
        opacity: 0.8,
      },
      {
        id: 'time-label',
        text: '{time}',
        uppercase: true,
        x: 22,
        y: 237,
        color: '#101010',
        fontSize: 28,
        lineHeight: 36,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Helvetica Neue',
        opacity: 0.8,
      },
      {
        id: 'pace-label',
        text: '[[{paceValue}]] {paceUnit}',
        uppercase: true,
        x: 152,
        y: 238,
        color: '#101010',
        fontSize: 20,
        fontWeight: '800',
        accentFontSize: 32,
        lineHeight: 36,
        letterSpacing: 0.6,
        fontFamily: 'Helvetica Neue',
        opacity: 0.8,
      },
      {
        id: 'cal-label',
        text: '[[{calories}]] Cal.',
        uppercase: true,
        x: 22,
        y: 308,
        color: '#101010',
        fontSize: 20,
        fontWeight: '800',
        accentFontSize: 32,
        lineHeight: 36,
        letterSpacing: 0.6,
        fontFamily: 'Helvetica Neue',
        opacity: 0.8,
      },
      {
        id: 'meta-date',
        text: '{date}',
        formatDate: 'dd MMM YYYY',
        uppercase: true,
        x: 22,
        y: 390,
        color: '#101010',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
        opacity: 0.8,
      },
      {
        id: 'meta-location',
        text: '{location}',
        uppercase: true,
        x: 22,
        y: 442,
        color: '#101010',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.6,
        fontFamily: 'Arial',
        opacity: 0.8,
      },
      {
        id: 'meta-name',
        text: '{activityName}',
        uppercase: true,
        x: 0,
        y: 542,
        color: '#101010',
        fontSize: 16,
        fontWeight: '900',
        letterSpacing: 0.6,
        fontFamily: 'Helvetica Neue',
        width: 360,
        align: 'center',
        opacity: 0.8,
      },
    ],
  },
];

export const DEFAULT_PREVIEW_TEMPLATE_ID =
  PREVIEW_TEMPLATES[0]?.id ?? 'template-runners-zine';

export function getPreviewTemplateById(templateId: string | null | undefined) {
  if (!templateId) return null;
  return PREVIEW_TEMPLATES.find((item) => item.id === templateId) ?? null;
}
