import { FontPreset, StatsTemplate } from '@/types/preview';

export const STORY_WIDTH = 360;
export const STORY_HEIGHT = 640;
export const MAX_VIDEO_DURATION_SECONDS = 30;
export const CHECKER_SIZE = 20;

export const TEMPLATES: StatsTemplate[] = [
  {
    id: 'hero',
    name: 'Hero',
    layout: 'row',
    x: 16,
    y: 435,
    width: 288,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'vertical',
    name: 'Vertical',
    layout: 'stack',
    premium: false,
    x: 70,
    y: 336,
    width: 300,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'compact',
    name: 'Compact',
    layout: 'inline',
    premium: false,
    x: 20,
    y: 480,
    width: 280,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'columns',
    name: 'Columns',
    layout: 'right',
    premium: false,
    x: 12,
    y: 490,
    width: 350,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'grid-2x2',
    name: 'Grid 2x2',
    layout: 'grid',
    premium: true,
    x: 18,
    y: 420,
    width: 284,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
];

export const FONT_PRESETS: FontPreset[] = [
  {
    id: 'avenir',
    name: 'Avenir Next',
    family: 'Avenir Next',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'rounded',
    name: 'Gill Sans',
    family: 'Gill Sans',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'condensed',
    name: 'sans-serif-condensed',
    family: 'sans-serif-condensed',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'georgia',
    name: 'Georgia',
    family: 'Georgia',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'helvetica',
    name: 'Helvetica Neue',
    family: 'Helvetica Neue',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'times',
    name: 'Times New Roman',
    family: 'Times New Roman',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'courier',
    name: 'Courier New',
    family: 'Courier New',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'verdana',
    name: 'Verdana',
    family: 'Verdana',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'trebuchet',
    name: 'Trebuchet MS',
    family: 'Trebuchet MS',
    weightTitle: '700',
    weightValue: '800',
  },
];
