import { FontPreset, StatsLayout } from '@/types/preview';

export const STORY_WIDTH = 360;
export const STORY_HEIGHT = 640;
export const MAX_VIDEO_DURATION_SECONDS = 30;
export const CHECKER_SIZE = 20;

export const TEMPLATES: StatsLayout[] = [
  {
    id: 'hero',
    name: 'Hero',
    layout: 'hero',
    x: 16,
    y: 435,
    width: 288,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'vertical',
    name: 'Vertical',
    layout: 'vertical',
    premium: false,
    x: 70,
    y: 336,
    width: 300,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'compact',
    name: 'Compact',
    layout: 'compact',
    premium: false,
    x: 20,
    y: 480,
    width: 280,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'columns',
    name: 'Columns',
    layout: 'columns',
    premium: false,
    x: 12,
    y: 490,
    width: 350,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'grid-2x2',
    name: 'Grid 2x2',
    layout: 'grid-2x2',
    premium: false,
    x: 18,
    y: 420,
    width: 284,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'glass-row',
    name: 'Glass Row',
    layout: 'glass-row',
    premium: false,
    x: 16,
    y: 420,
    width: 328,
    backgroundColor: 'rgba(12,18,28,0.42)',
    borderColor: 'rgba(255,255,255,0.30)',
    borderWidth: 1,
    radius: 22,
  },
  {
    id: 'soft-stack',
    name: 'Soft Stack',
    layout: 'soft-stack',
    premium: true,
    x: 36,
    y: 300,
    width: 288,
    backgroundColor: 'rgba(6,8,14,0.56)',
    borderColor: 'rgba(212,255,84,0.42)',
    borderWidth: 1,
    radius: 18,
  },
  {
    id: 'pill-inline',
    name: 'Pill Inline',
    layout: 'pill-inline',
    premium: false,
    x: 24,
    y: 496,
    width: 312,
    backgroundColor: 'rgba(8,12,20,0.62)',
    borderColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    radius: 999,
  },
  {
    id: 'card-columns',
    name: 'Card Columns',
    layout: 'card-columns',
    premium: false,
    x: 14,
    y: 468,
    width: 332,
    backgroundColor: 'rgba(10,14,24,0.65)',
    borderColor: 'rgba(212,255,84,0.30)',
    borderWidth: 1,
    radius: 16,
  },
  {
    id: 'panel-grid',
    name: 'Panel Grid',
    layout: 'panel-grid',
    premium: false,
    x: 24,
    y: 402,
    width: 312,
    backgroundColor: 'rgba(10,15,24,0.62)',
    borderColor: 'rgba(255,255,255,0.20)',
    borderWidth: 1,
    radius: 20,
  },
  {
    id: 'sunset-hero',
    name: 'Sunset Hero',
    layout: 'sunset-hero',
    premium: false,
    x: 20,
    y: 220,
    width: 320,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'morning-glass',
    name: 'Morning Glass',
    layout: 'morning-glass',
    premium: false,
    x: 12,
    y: 286,
    width: 336,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
  {
    id: 'split-bold',
    name: 'Split Bold',
    layout: 'split-bold',
    premium: false,
    x: 24,
    y: 210,
    width: 212,
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    radius: 0,
  },
];

export const FONT_PRESETS: FontPreset[] = [
  {
    id: 'avenir',
    name: 'Avenir Next',
    family: 'Avenir Next',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'rounded',
    name: 'Gill Sans',
    family: 'Gill Sans',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'condensed',
    name: 'sans-serif-condensed',
    family: 'sans-serif-condensed',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'georgia',
    name: 'Georgia',
    family: 'Georgia',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'helvetica',
    name: 'Helvetica Neue',
    family: 'Helvetica Neue',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'times',
    name: 'Times New Roman',
    family: 'Times New Roman',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'courier',
    name: 'Courier New',
    family: 'Courier New',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'verdana',
    name: 'Verdana',
    family: 'Verdana',
    weightTitle: '700',
    weightValue: '800',
  },
  {
    id: 'trebuchet',
    name: 'Trebuchet MS',
    family: 'Trebuchet MS',
    weightTitle: '700',
    weightValue: '800',
  },
];
